// Created by: Braxton Fair
// Created on: 02/05/2021
using System;

/*
 * THE PROBLEM:
 *
 * 2.) Calculate the number of legs (Easy)
 *
 * In this problem the user will input the number of sheep, cows, chickens, goats,
 * cats, dogs and farmers on a farm, and your program will return the number of legs.
 *
 * Sample Input:
 * CalcLegs(2,3,10,6,4, 2, 2)
 *
 * Sample Output (Generated by ToString()):
 *
 * There are 92 legs on the farm:
 * 2 sheep = 8 legs
 * 3 cows = 12 legs
 * 10 chickens = 20 legs
 * 6 goats = 24 legs
 * 4 cats = 16 legs
 * 2 dogs = 8 legs
 * 2 farmers = 4 legs
 */

namespace _2
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Legs numberOfLegs = new Legs(2, 3, 10, 6, 4, 2, 2); 

            Console.WriteLine(numberOfLegs.ToString());
            
            Console.WriteLine("Press any key to continue.");
            Console.ReadKey();
        }
    }
}
