// Created by: Braxton Fair
// Created on: 02/05/2021

/*
 * THE PROBLEM:
 *
 * 1.) Create a program that can convert a number of Days, Hours, 
 * or Minutes into seconds.  (Easy)
 *
 * Sample Input:
 * "Enter the number of Days"
 * 10
 *
 * Sample Output (Generated by ToString()):
 *
 * 10 days equals
 * 240 hours
 * 14400 minutes
 * 864000 seconds
 */
using System;

namespace _1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Enter the number of days to convert.");

            Converter ourConverter = new Converter(Convert.ToInt32(Console.ReadLine()));
            Console.WriteLine(ourConverter);
 
            Converter ourConverter1 = new Converter();
            Console.WriteLine("\n------\nDefault constructor:\n" + ourConverter1);

            Console.WriteLine("Press any key to continue.");
            Console.ReadKey();
        }
    }
}
